"""Initial Migration

Revision ID: 59f3bb5e6820
Revises: 6525fb1c9d8b
Create Date: 2021-02-28 21:22:40.684484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59f3bb5e6820'
down_revision = '6525fb1c9d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tempTank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('lat', sa.String(), nullable=False),
    sa.Column('long', sa.String(), nullable=False),
    sa.Column('percentage_full', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location')
    )
    op.drop_table('dishes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vegan', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('img', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dishes_pkey'),
    sa.UniqueConstraint('name', name='dishes_name_key')
    )
    op.drop_table('tempTank')
    # ### end Alembic commands ###
