"""Initial Migration

Revision ID: 6525fb1c9d8b
Revises: 
Create Date: 2021-02-28 17:25:28.215922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6525fb1c9d8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vegan', sa.Boolean(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dishes')
    # ### end Alembic commands ###
